### ISSUE TITLE
Please add usernames

### ISSUE THREAD

**Issue by 102plee** [joeyshi12/joeys-games#6]
I'd like to have my username above my avatar while gaming. 

![image](https://user-images.githubusercontent.com/16752627/147423498-8aabb57f-2e00-47e1-afe3-6bed77d1ddea.png)

**Comment by joeyshi12** [comment]
Please refrain from using insults as the username :(

**Comment by joeyshi12** [comment]
Will begin work once #5 has been addressed

**Comment by joeyshi12** [comment]
Implemented in https://github.com/joeyshi12/platform-party/issues/5
